language: python

python:
  - '2.7'

env:
  global:
    # Our .env file uses Windows-specific commands so we need to override it
    - PIPENV_DOTENV_LOCATION=".env-nix"

install:
  - 'pip install pipenv'
  - 'cd Scripts && pipenv --python 2.7 install --dev'

script:
  - 'pipenv run pytest tests'
#  - 'cd Scripts && pipenv run pytest tests'
#  - 'cd Scripts && python -m pytest --cov=pyblizzard tests --cov-report=xml'
#after_success:
#  - 'python-codacy-coverage -r coverage.xml'
