~# *** tee_vuorovalimuuttujat.mac
~#
~# Makro tekee pysakkimakron tarvitsemia extra-attribuutteja vuorovaleja varten (TE 11.5.2017)
~# Muista ajaa joka skenaarioon
~# ~<tee_vuorovalimuuttujat.mac
~# 
 2.42
 2
 1 \solmumuuttuja
 @hsl
 onko HSL-alue
 0
~#
 2
 3 \linjamuuttuja
 @hwaht
 vuorovali aht
 0
~#
 2
 3 \linjamuuttuja
 @hwiht
 vuorovali iht
 0
~#
 2
 3 \linjamuuttuja
 @hwpt
 vuorovali pt
 0
~#
 2
 3 \linjamuuttuja
 @ajoai
 ajoaika
 0
~#
 q